spring.application.name=automatizacao
spring.datasource.url=jdbc:postgresql://db.rugvgtpbgupejtugznyz.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=kaylaralet2025
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.springframework.transaction=DEBUG
logging.level.org.hibernate=DEBUG
logging.level.org.springframework.orm.jpa=DEBUG
