spring.application.name=automatizacao
spring.datasource.url=jdbc:postgresql://db.rugvgtpbgupejtugznyz.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=kaylaralet2025
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
